version: 2.19.0.{build}
image: Visual Studio 2022


environment:
  matrix:
  - PlatformToolset: v143

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64
    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32
    - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild RainLexer.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "x64-$env:CONFIGURATION\RainLexer.dll" -FileName RainLexer.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "x32-$env:CONFIGURATION\RainLexer.dll" -FileName RainLexer.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v143") {
            if($env:PLATFORM_INPUT -eq "x64"){
            $ZipFileName = "RainLexer_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            Remove-Item x64-$env:CONFIGURATION\*.ilk
            Remove-Item x64-$env:CONFIGURATION\*.pdb
            7z a $ZipFileName x64-$env:CONFIGURATION\*
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
            $ZipFileName = "RainLexer_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            Remove-Item x32-$env:CONFIGURATION\*.ilk
            Remove-Item x32-$env:CONFIGURATION\*.pdb
            7z a $ZipFileName x32-$env:CONFIGURATION\*
            }
        }

artifacts:
  - path: RainLexer_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v143
        configuration: Release
